shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.catppuccin-fzf]
github = "catppuccin/fzf"
use = ["themes/catppuccin-fzf-mocha.sh"]
apply = ["defer"]

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.smartcache]
github = "QuarticCat/zsh-smartcache"
