.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/frankerfacez@frankerfacez.com.xpi:
  type: file
  url: https://cdn.frankerfacez.com/script/frankerfacez-4.0-an+fx.xpi

{{ $root := .}}
{{ range $font := .nerdfonts.fonts }}
.local/share/fonts/NerdFonts/{{ $font }}:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $root.nerdfonts.version }}/{{ $font }}.zip
  exclude:
    - "*Windows Compatible*.ttf"
    - "*Windows Compatible*.otf"
    - "LICENSE"
    - "*.txt"
    - "*.md"
    - .uuid
{{ end }}

.config/tmux/plugins/tpm:
  type: "git-repo"
  url: "https://github.com/tmux-plugins/tpm.git"
