packages: git curl direnv wget ripgrep jq flatpak fish luajit neovim tmux
rustPackages: cargo-update cargo-info bacon
githubPackages: jesseduffield/lazygit topgrade-rs/topgrade sharkdp/fd sharkdp/bat jdx/rtx cargo-bins/cargo-binstall cargo-lambda/cargo-lambda superfly/flyctl

git:
  name: Rob Brazier
  host: brzr.co

gitHosts:
  - name: git.sr.ht
  - name: "*.runners.sr.ht"
  - name: github.com !*.github.com
  - name: codeberg.org

distros:
  arch:
    - arch
  ubuntu:
    - ubuntu debian
    - ubuntu
  fedora:
    - fedora
    - nobara

tools:
  neovim: stable
  nodejs: "latest"
  python: "pypy3.9"
  php: ""

ssh:
  types:
    # SSH Key for git access
    git: ed25519
    # SSH Key for normal access
    id: ed25519
  aliases:
    start:
      user: start
    hass:
      user: root
    apps:
      user: root
    pve:
      user: root
    izanagi:
      user: rob
  aliasSuffix: lan.brazier.cloud

nerdfonts:
  fonts:
    - SourceCodePro
    - JetBrainsMono
    - FiraCode
    - FiraMono
    - DroidSansMono
    - Iosevka
