packages: git curl direnv wget ripgrep jq flatpak fish luajit neovim
rustPackages: rtx-cli cargo-update topgrade pfetch cargo-info bacon fd-find
gitrelPackages: jesseduffield/lazygit

git:
  name: Rob Brazier
  email: git@brzr.co

gitHosts:
  - name: git.sr.ht
  - name: "*.runners.sr.ht"
  - name: github.com
  - name: codeberg.org
  - name: git.brazier.dev
    port: "2727"

distros:
  arch:
    - arch
  ubuntu:
    - ubuntu debian
    - ubuntu
  fedora:
    - fedora
    - nobara

ssh:
  types:
    # SSH Key for git access
    git: ed25519
    # SSH Key for normal access
    id: ed25519
  aliases:
    start:
      user: start
      # host: start
    hass:
      user: root
      # host: hass
    apps:
      user: root
      # host: apps
    pve:
      user: root
      # host: pve
  aliasSuffix: lan.brazier.cloud

nerdfonts:
  version: "2.3.3"
  fonts:
    - SourceCodePro
    - JetBrainsMono
    - FiraCode
    - FiraMono
    - DroidSansMono
    - Iosevka
