# {{ $root := .}}
# {{ range $font := .nerdfonts.fonts }}
[".local/share/fonts/NerdFonts/{{ $font }}"]
type = "archive"
url = 'https://github.com/ryanoasis/nerd-fonts/releases/download/{{(gitHubLatestRelease "ryanoasis/nerd-fonts").TagName}}/{{ $font }}.zip'
exclude = [
    "*Windows Compatible*.ttf",
    "*Windows Compatible*.otf",
    "LICENSE",
    "*.txt",
    "*.md",
    ".uuid",
]
# {{ end }}

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"

[".config/btop/themes"]
type = "archive"
url = "https://api.github.com/repos/catppuccin/btop/tarball"
stripComponents = 2
include = ["*/themes/**"]

[".config/firefox/chrome"]
type = "archive"
url = 'https://github.com/soulhotel/FF-ULTIMA/archive/refs/tags/{{(gitHubLatestRelease "soulhotel/FF-ULTIMA").TagName}}.zip'
stripComponents = 1
exact = true

[".local/share/chezmoi/.chezmoitemplates/firefox/betterfox"]
type = "archive"
url = 'https://github.com/yokoffing/Betterfox/archive/refs/tags/{{(gitHubLatestRelease "yokoffing/Betterfox").TagName}}.zip'
stripComponents = 1
include = ["*/Fastfox.js", "*/Peskyfox.js", "*/Securefox.js"]
