packages: git curl direnv wget ripgrep jq flatpak fish luajit neovim tmux
rustPackages: rtx-cli cargo-update topgrade pfetch cargo-info bacon fd-find bat cargo-lambda
gitrelPackages: jesseduffield/lazygit

git:
  name: Rob Brazier
  email: git@brzr.co

gitHosts:
  - name: git.sr.ht
  - name: "*.runners.sr.ht"
  - name: github.com
  - name: codeberg.org
  - name: git.brazier.dev
    port: "2727"

distros:
  arch:
    - arch
  ubuntu:
    - ubuntu debian
    - ubuntu
  fedora:
    - fedora
    - nobara

tools:
  neovim: stable
  nodejs: "lts"
  pnpm: "latest"
  python: "pypy3.9"
  php: ""
  poetry: "latest"
  pipx: "latest"
  zig: "latest"

ssh:
  types:
    # SSH Key for git access
    git: ed25519
    # SSH Key for normal access
    id: ed25519
  aliases:
    start:
      user: start
    hass:
      user: root
    apps:
      user: root
    pve:
      user: root
    izanagi:
      user: rob
  aliasSuffix: lan.brazier.cloud

nerdfonts:
  version: "3.0.1"
  fonts:
    - SourceCodePro
    - JetBrainsMono
    - FiraCode
    - FiraMono
    - DroidSansMono
    - Iosevka
