# {{ $root := .}}
# {{ range $font := .nerdfonts.fonts }}
[".local/share/fonts/NerdFonts/{{ $font }}"]
type = "archive"
url = 'https://github.com/ryanoasis/nerd-fonts/releases/download/{{(gitHubLatestRelease "ryanoasis/nerd-fonts").TagName}}/{{ $font }}.zip'
exclude = [
    "*Windows Compatible*.ttf",
    "*Windows Compatible*.otf",
    "LICENSE",
    "*.txt",
    "*.md",
    ".uuid",
]
# {{ end }}

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"

[".config/btop/themes"]
type = "archive"
url = "https://api.github.com/repos/catppuccin/btop/tarball"
stripComponents = 2
include = ["*/themes/**"]
