packages = [
	"bat",
	"curl",
	"fd-find",
	"flatpak",
	"fzf",
	"git",
	"jq",
	"luajit",
	"neovim",
	"rbw",
	"ripgrep",
	"tmux",
	"wget",
	"zsh",
  "chezmoi",
]
flatpakPackages = [
	"com.github.tchx84.Flatseal",
	"dev.vencord.Vesktop",
	"io.github.giantpinkrobots.flatsweep",
	"io.missioncenter.MissionCenter",
	"it.mijorus.gearlever",
	"org.localsend.localsend_app",
]
binPackages = [
	"github.com/jj-vcs/jj",
	"github.com/topgrade-rs/topgrade",
  "github.com/rossmacarthur/sheldon",
]
cargoPackages = [
	"cargo-update",
	"cargo-info",
	"bob-nvim",
]
shell = "zsh"

[git]
name = "Rob Brazier"
host = "brzr.co"

[[gitHosts]]
name = "github.com !*.github.com"
hostname = "github.com"

[[gitHosts]]
name = "codeberg.org"

[[gitHosts]]
name = "alter.github.com"
hostname = "github.com"
identity = "alter"

[distros]
arch = ["arch"]
ubuntu = ["ubuntu debian", "ubuntu"]
fedora = ["fedora", "nobara"]

[ssh]
[ssh.lanUsers]
# jellyfin = "jellyfin"

[nerdfonts]
fonts = ["SourceCodePro", "JetBrainsMono", "FiraCode", "CascadiaCode"]
