packages: git curl direnv wget ripgrep jq flatpak fish neovim

git:
  name: Rob Brazier
  email: git@brzr.co

gitHosts:
  - git.sr.ht
  - '*.runners.sr.ht'
  - github.com
  - codeberg.org

distros:
  arch:
    - arch
  ubuntu:
    - ubuntu debian
    - ubuntu
  fedora:
    - fedora
    - nobara

ssh:
  types:
    # SSH Key for git access
    git: ed25519
    # SSH Key for normal access
    id: ed25519
  aliases:
    start:
      user: start
      # host: start
    hass:
      user: root
      # host: hass
    apps:
      user: root
      # host: apps
    pve:
      user: root
      # host: pve
  aliasSuffix: lan.brazier.cloud

nerdfonts:
  version: "2.3.3"
  fonts:
    - SourceCodePro
    - JetBrainsMono
    - FiraCode
    - FiraMono
    - DroidSansMono
    - Iosevka