.asdf:
  type: git-repo
  url: https://github.com/asdf-vm/asdf.git

.config/nvim/init.lua:
  type: file
  url: https://raw.githubusercontent.com/nvim-lua/kickstart.nvim/master/init.lua
  refreshPeriod: 168h