[settings]
experimental = true
disable_hints = ["outdated_bump"]

[tools]
"ubi:a-h/templ" = "latest"
"ubi:jandedobbeleer/oh-my-posh" = "latest"
"ubi:topgrade-rs/topgrade" = "latest"
bat = "latest"
bitwarden = "latest"
direnv = "latest"
fd = "latest"
flyctl = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
task = "latest"
usage = "latest"
zoxide = "latest"
