[settings]
experimental = true
disable_hints = ["outdated_bump"]

[tools]
go = "latest"
# neovim = "latest"
node = "latest"
usage = "latest"
python = "latest"
"ubi:cli/cli" = { version = "latest", exe = "gh" }
"ubi:go-task/task" = "latest"
"ubi:a-h/templ" = "latest"
"ubi:superfly/flyctl" = "latest"
"ubi:jandedobbeleer/oh-my-posh" = "latest"
"ubi:topgrade-rs/topgrade" = "latest"
