[settings]
experimental = true
disable_hints = ["outdated_bump"]

[tools]
"ubi:a-h/templ" = "latest"
"ubi:go-task/task" = "latest"
"ubi:jandedobbeleer/oh-my-posh" = "latest"
"ubi:jdx/usage" = "latest"
"ubi:superfly/flyctl" = "latest"
"ubi:topgrade-rs/topgrade" = "latest"
bitwarden = "latest"
direnv = "latest"
gh = "latest"
go = "latest"
neovim = "latest"
node = "latest"
python = "latest"
zoxide = "latest"
