[misc]
skip_notify = true
no_self_update = true
pre_sudo = true

disable = ["bun", "nix", "cargo", "rustup"]

[commands]
"mise upgrade" = "mise self-update --yes"
"chezmoi upgrade" = "chezmoi upgrade"
