[tools]
"aqua:doy/rbw" = "latest"
"cargo:cargo-info" = "latest"
cargo-binstall = "latest"
opencode = "latest"
gh = "latest"
git-cliff = "latest"
go = "latest"
node = "lts"
python = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
